export const LOAD_GROUP_POSTS = "LOAD-GROUP-POSTS";
export const GET_GROUP = "GET_GROUP";
export const TOGGLE_GROUPPAGE_LIKE = "TOGGLE_GROUPPAGE_LIKE";
export const SUBSCRIBE_GROUP = "SUBSCRIBE_GROUP";
export const EDIT_DESCRIPTION = "EDIT_DESCRIPTION";

export const SET_ALL_GROUPS_LIST = 'SET_ALL_GROUPS_LIST';
export const SET_TOP_GROUPS_LIST = 'SET_TOP_GROUPS_LIST';
export const SUBSCRIBE_GROUP_FROM_LIST = 'SUBSCRIBE_GROUP_FROM_LIST';
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP';

export const FETCH_POST_COMMENTS = "FETCH_POST_COMMENTS";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const UPDATE_POST = "UPDATE_POST";
export const TOGGLE_LIKE = "TOGGLE_LIKE";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const LIKE_REPLY = "LIKE_REPLY";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_REPLY = "ADD_REPLY";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_REPLY = "EDIT_REPLY";
export const DELETE_REPLY = "DELETE_REPLY";
export const SORT_COMMENTS = "SORT_COMMENTS";

export const SET_POSTS = "SET_POSTS";
export const LOAD_MORE_POSTS = "LOAD_MORE_POSTS";
export const DELETE_POST = "DELETE_POST";


export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const TOGGLE_SEARCH_LIKE = 'TOGGLE_SEARCH_LIKE';
export const LOAD_SEARCH_POSTS = 'LOAD_SEARCH_POSTS';

export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";

export const FETCH_USER = "FETCH_USER";
export const TOGGLE_USERPAGE_LIKE = "TOGGLE_USERPAGE_LIKE";
export const LOAD_USER_POSTS = "LOAD_USER_POSTS";

export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
export const SET_USER = "SET_USER";
export const SET_AVATAR = "SET_AVATAR";
export const REMOVE_AVATAR = "REMOVE_AVATAR";


export const SET_NOTIFICATION = "SET_NOTIFICATION"
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION"